### ISSUE TITLE
Error "type object 'MyCompositeField' has no attribute 'get_internal_type'"" when used for Func output_field

### ISSUE THREAD

**Issue by OJFord** [bikeshedder/django-composite-field#3]
Using a `CompositeField` as the `output_field` in a (an outer) `django.db.models.Func`, such as within a call to `qs.aggregate()`, results in:
> type object 'MyCompositeField' has no attribute 'get_internal_type'"

For example:
```python
MyModel.objects.aggregate(
    min=Min(
        Func(F("a"), F("b"), function="construct_composite", output_field=MyCompositeField()),
    ),
)
```

**Comment by bikeshedder** [comment]
The way composite fields are implemented is to create fields internally on the model (added inside the `contribute_to_class` method) and provide a proxy for accessing those "sub fields" via the dot-notation.

`foo.coord.lat = 12.345` is basicly identical to `foo.coord_lat = 12.345` because `foo.coord` is a proxy that provides `__setattr__` and `__getattr__` methods.

For aggregations to work it would require an entirely different code path. That field is not part of the model during class creation and therefore `contribute_to_class` is never triggered.

I might be completely off here, but I'm not sure if this can work at all the way composite fields are implemented at the moment. If you find a way to support this feel free to open a PR.

**Comment by OJFord** [comment]
Ah I see, thanks for the info.

**Comment by bikeshedder** [comment]
I tried to explain the implementation details here: https://django-composite-field.readthedocs.io/en/latest/usage.html#how-does-it-work

A `CompositeField` is no "real field". It just creates the sub fields inside the `contribute_to_class` method and registers itself as a private/virtual field and provides the proxy property. Apart from that it is completely transparent to the Django ORM.
